FROM node:latest

USER node
WORKDIR /home/node

RUN mkdir ~/.npm-global \
  && npm config set prefix '~/.npm-global' \
  && echo "export PATH=~/.npm-global/bin:$PATH" >> ~/.bashrc

RUN exec /bin/bash -l

RUN npm install -g wscat

ENV PORT 3000
EXPOSE 3000

CMD /bin/bash
