FROM node:latest

USER node
WORKDIR /home/node

RUN mkdir ~/.npm-global \
  && npm config set prefix '~/.npm-global' \
  && echo "export PATH=~/.npm-global/bin:$PATH" >> ~/.bashrc

RUN exec /bin/bash -l

RUN npm install -g npm \
  && npm install -g wscat yarn

COPY --chown=node:node ./src/server/front/package.json /home/node/gochat_front/package.json
WORKDIR /home/node/gochat_front

RUN yarn install

ENTRYPOINT ["yarn"]
CMD ["start"]
