FROM node:latest

USER node
WORKDIR /home/node

RUN mkdir ~/.npm-global \
  && npm config set prefix '~/.npm-global' \
  && echo "export PATH=~/.npm-global/bin:$PATH" >> ~/.bashrc

RUN exec /bin/bash -l

RUN npm install -g wscat yarn

COPY ./src/server/front /home/node/gochat_front
WORKDIR /home/node/gochat_front
RUN yarn install

ENV PORT 3000
EXPOSE 3000

CMD yarn start
